"""add export comments

Revision ID: 3da8a652a9e0
Revises: bcbb758597a2
Create Date: 2016-09-07 19:16:26.726267

"""

# revision identifiers, used by Alembic.
revision = '3da8a652a9e0'
down_revision = 'bcbb758597a2'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('export_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_create', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('format', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('export_comments')
    ### end Alembic commands ###
