"""add notifications

Revision ID: f771eb1ffa0f
Revises: 8f937b231579
Create Date: 2016-09-07 21:04:05.916063

"""

# revision identifiers, used by Alembic.
revision = 'f771eb1ffa0f'
down_revision = '8f937b231579'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_create', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', postgresql.ENUM('comment', name='action'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    ### end Alembic commands ###
