"""Initial models

Revision ID: 3bff55d5155a
Revises: 
Create Date: 2016-09-06 16:14:41.708225

"""

# revision identifiers, used by Alembic.
revision = '3bff55d5155a'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('essence_id', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_update', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('tree_id', sa.Integer(), nullable=True),
    sa.Column('rgt', sa.Integer(), nullable=False),
    sa.Column('lft', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['essence_id'], ['entities.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('comments_level_idx', 'comments', ['level'], unique=False)
    op.create_index('comments_lft_idx', 'comments', ['lft'], unique=False)
    op.create_index('comments_rgt_idx', 'comments', ['rgt'], unique=False)
    op.create_index(op.f('ix_comments_user_id'), 'comments', ['user_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_user_id'), table_name='comments')
    op.drop_index('comments_rgt_idx', table_name='comments')
    op.drop_index('comments_lft_idx', table_name='comments')
    op.drop_index('comments_level_idx', table_name='comments')
    op.drop_table('comments')
    op.drop_table('entities')
    ### end Alembic commands ###
