"""add history comment

Revision ID: bcbb758597a2
Revises: f5186d0981c9
Create Date: 2016-09-07 16:38:52.167840

"""

# revision identifiers, used by Alembic.
revision = 'bcbb758597a2'
down_revision = 'f5186d0981c9'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments_history',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('date_update', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('event_user', sa.Integer(), nullable=True),
    sa.Column('event_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('event_type', postgresql.ENUM('delete', 'add', 'update', name='event_type'), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_comments_history_event_user'), 'comments_history', ['event_user'], unique=False)
    op.create_index(op.f('ix_comments_history_user_id'), 'comments_history', ['user_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comments_history_user_id'), table_name='comments_history')
    op.drop_index(op.f('ix_comments_history_event_user'), table_name='comments_history')
    op.drop_table('comments_history')
    ### end Alembic commands ###
