"""add base entity

Revision ID: c604c545e634
Revises: 82ac543ff47b
Create Date: 2016-09-07 22:45:07.071423

"""

# revision identifiers, used by Alembic.
from exness_comment.models import Entity

revision = 'c604c545e634'
down_revision = '82ac543ff47b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.insert(Entity).values(name='Посты'))
    op.execute(sa.insert(Entity).values(name='Блоги'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.delete(Entity))
    ### end Alembic commands ###
