sudo: required

language: python

env:
  - DB_NAME=test_database DB_PWD=qwerty DB_USER=test_user DB_HOST=localhost

python:
  - "3.5"
  - "nightly" # currently points to 3.6-dev

install: 
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
  
services:
  - postgresql
  - docker
  
before_install:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker build -t virmir49/exness_comment .;
    fi
  
before_script:
  - psql -c 'CREATE DATABASE test_database;' -U postgres
  - psql -c "CREATE USER test_user WITH password 'qwerty';" -U postgres
  - psql -c "ALTER USER test_user WITH SUPERUSER;" -U postgres
  
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push USER/REPO;
    fi
    
script:
  - py.test
